### ISSUE TITLE
Not having functionality to Authenticate captured Biometric details with UIDAI Server(AUA Server)

### ISSUE THREAD

**Issue by neeleshatale** [senthalan2/react-native-rdservice-fingerprintscanner#5]
Currently this library provides only capturing biometric details. Can you please add functionality to Authenticate captured date with UIDAI server

**Comment by senthalan2** [comment]
Hi @neeleshatale,

This Library only used to capture the biometric data from the registered biometric devices.

1. In order to authenticate captured data with the UIDAI (Unique Identification Authority of India) server, you will need to register your app with the UIDAI and obtain an API key and a certificate. 

2. Then you will need to use the UIDAI's authentication API and make an HTTP request to it with the required data that should be encrypted using the certificate obtained in step 1.

you can achieve this functionality by using REST API.

Thank you.
